# Generated by Django 3.1.6 on 2021-03-19 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainuser',
            options={'ordering': ('first_name', 'last_name')},
        ),
    ]
